# Makefile
# 28, Sep 2019 created by Oyadomari
# 
# Compile the RINGsize2.7_C and create the shared library" RINGsize2.7_C.so".
# The shared library is imported to the python script " RINGSize2.7.C.py".

RINGsize2.7_C: RINGsize2.7_C.c
	gcc -std=c99 -shared -fPIC RINGsize2.7_C.c -o RINGsize2.7_C.so
